# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run Unit Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  unit-test:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 16]

    steps:
    - uses: actions/checkout@v2
    - name: Cache Local Maven Repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Run Unit Tests With Maven
      run: mvn surefire:test --file pom.xml

  label:
    name: Label as Release Candidate
    runs-on: ubuntu-latest
    needs: [ unit-test ]
    if: contains( github.event.pull_request.head.ref, 'dependabot/maven/org.liquibase-liquibase-core' )
    steps:
      - uses: actions/checkout@v2
      - name: Set Version Tag ENV
        run: ./.github/set-version-from-head.sh ${{ github.event.pull_request.head.ref }}

      - run: echo $VERSION_TAG
          

      # bump version
      # create tag
#      - run: ./.github/add-label-to-pull-request.sh
#        env:
#          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
#          GITHUB_ISSUE_URL: ${{ github.event.pull_request._links.issue.href }}
#          GITHUB_LABEL: "Extension Release Candidate :rocket:"
#      - run: ./.github/add-comment-to-pull-request.sh
#        env:
#          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
#          GITHUB_ISSUE_URL: ${{ github.event.pull_request._links.issue.href }}
#          GITHUB_COMMENT: "<h2> ⚠️  Reminder</h2>Release Candidate pull requests will automatically release when merged.<br /><br />Please review and merge all other pull requests prior to merging this request."