# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run Unit Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  unit-test:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 16]

    steps:
    - uses: actions/checkout@v2
    - name: Cache Local Maven Repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Run Unit Tests With Maven
      run: mvn surefire:test --file pom.xml

  label:
    name: Label as Release Candidate
    runs-on: ubuntu-latest
    needs: [ unit-test ]
    if: contains( github.event.pull_request.head.ref, 'dependabot/maven/org.liquibase-liquibase-core' )
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set Version Tag ENV
        run: ./.github/set-version-from-head.sh ${{ github.event.pull_request.head.ref }}

      - run: echo $VERSION_TAG

      - name: Configure git user
        run: |
          git config user.name "liquibot"
          git config user.email "liquibot@liquibase.org"

      - name: Bump POM Version for Next Release
        run: |
          mvn versions:set -DnewVersion=$VERSION_TAG
          git add pom.xml
          git tag -a -m "Version Bumped to $VERSION_TAG" liquibase-postgresql-$VERSION_TAG
          git commit -m "Version Bumped to $VERSION_TAG"
          git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" HEAD:${{ github.event.pull_request.head.ref }} --follow-tags --tags

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          message: "Version Bumped to $VERSION_TAG"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true

#      - run: ./.github/add-label-to-pull-request.sh
#        env:
#          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
#          GITHUB_ISSUE_URL: ${{ github.event.pull_request._links.issue.href }}
#          GITHUB_LABEL: "Extension Release Candidate :rocket:"
#      - run: ./.github/add-comment-to-pull-request.sh
#        env:
#          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
#          GITHUB_ISSUE_URL: ${{ github.event.pull_request._links.issue.href }}
#          GITHUB_COMMENT: "<h2> ⚠️  Reminder</h2>Release Candidate pull requests will automatically release when merged.<br /><br />Please review and merge all other pull requests prior to merging this request."